version: '3.8'

services:
  zookeeper-watchguard:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper-watchguard
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - watchguard-zookeeper-data:/var/lib/zookeeper
    networks:
      - watchguard-network

  kafka-watchguard:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka-watchguard
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-watchguard:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    depends_on:
      - zookeeper-watchguard
    volumes:
      - watchguard-kafka-data:/var/lib/kafka/data
    networks:
      - watchguard-network

volumes:
  watchguard-zookeeper-data:
    driver: local
  watchguard-kafka-data:
    driver: local

networks:
  watchguard-network:
    driver: bridge