spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic: topic
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

message:
  config:
    produce-interval-ms: 2000
    dump-interval-ms: 4000
    max-messages: 100
    output-directory: message-output